# Site settings
title: Douglas Wright
email: douglas.wrightiii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 freeCodeCamp, Codecademy, hackerrank, portfolio page, front-end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spazcool.com" # the base hostname & protocol for your site
twitter_username: SpazC00l
github_username:  Spazcool

# Build settings
markdown: kramdown

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

